import { useMemo, useState } from 'react';
import { ArrowRight, BadgeCheck, CalendarDays, ChevronLeft, ChevronRight, CircleCheck, Download, Home as HomeIcon, MessageCircle, Phone, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'wouter';
import { projects } from '@/data/projects';
import { CONTACT, ProjectCard, SectionHeading, Shell, downloadBrochure } from '@/components/site';
import { FadeIn, StaggerContainer, StaggerItem } from '@/components/animations';

const reviews = [
  { quote: 'The team answered every question without making us feel rushed. We visited on Saturday and knew exactly what our next step was.', name: 'Mona & Karim', detail: 'Homeowners, Capital Hills New Cairo' },
  { quote: 'I was buying for my parents, so clarity mattered. The payment schedule and walkthrough made the decision straightforward.', name: 'Hany M.', detail: 'Buyer, Hillside October' },
  { quote: 'What stood out was the follow-through. Someone picked up every time I called and explained the small details.', name: 'Nour A.', detail: 'Homeowner, Marina Court Ain Sokhna' },
];

export default function Home() {
  const [city, setCity] = useState('all');
  const [budget, setBudget] = useState('all');
  const [type, setType] = useState('all');
  const [review, setReview] = useState(0);
  const filtered = useMemo(() => projects.filter((project) => (city === 'all' || project.city === city) && (budget === 'all' || (budget === 'under' ? project.startingPrice < 3000000 : project.startingPrice >= 3000000)) && (type === 'all' || project.unitTypes.some((unit) => unit.includes(type)))), [city, budget, type]);
  return <Shell>
    <main>
       <section className="relative min-h-[680px] bg-[#3d0f14] pt-28 text-[#fff7e9] md:min-h-[720px]">
        <div className="absolute inset-0 opacity-30"><img src="https://images.pexels.com/photos/7031603/pexels-photo-7031603.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="" className="h-full w-full object-cover" /></div><div className="absolute inset-0 bg-[linear-gradient(90deg,#3c1d2a_5%,rgba(86,41,58,.83)_52%,rgba(86,41,58,.3))]" />
        <div className="container-shell relative grid items-end gap-12 pb-36 md:grid-cols-[1.1fr_.9fr] md:pb-44">
           <StaggerContainer className="max-w-xl"><StaggerItem><p className="eyebrow">Homes worth coming home to</p></StaggerItem><StaggerItem><h1 className="mt-5 font-display text-5xl leading-[.98] tracking-[-.02em] md:text-7xl">A clear path to <span className="text-[#d9ad51]">your place.</span></h1></StaggerItem><StaggerItem><p className="mt-6 max-w-md text-base leading-7 text-[#ead9cc]">Thoughtfully planned homes, clear payment plans, and a real person ready to help you take the next step in Egypt.</p></StaggerItem><StaggerItem><div className="mt-8 grid max-w-[620px] grid-cols-1 gap-3 sm:grid-cols-3"><a href={CONTACT.tel} className="focus-ring inline-flex items-center justify-center gap-2 rounded-md bg-[#c49743] px-4 py-3 text-sm font-bold text-[#3c1d2a]" data-testid="link-hero-call">Call now <Phone size={15} /></a><a href={CONTACT.whatsapp} target="_blank" rel="noreferrer" className="focus-ring inline-flex items-center justify-center gap-2 rounded-md border border-[#ead8ba]/50 px-4 py-3 text-sm font-bold text-[#fff7e9]" data-testid="link-hero-whatsapp">WhatsApp <MessageCircle size={15} /></a><button onClick={() => downloadBrochure(projects[0])} className="focus-ring inline-flex items-center justify-center gap-2 rounded-md border border-[#ead8ba]/50 px-4 py-3 text-sm font-bold text-[#fff7e9]" data-testid="button-hero-brochure">Request brochure <Download size={15} /></button><Link href="/contact" className="focus-ring col-span-1 inline-flex items-center justify-center gap-2 rounded-md bg-[#fff8ea] px-4 py-4 text-sm font-bold text-[#3c1d2a] sm:col-span-3 hover:bg-[#d9ad51]" data-testid="link-hero-book-viewing">Book a Viewing <CalendarDays size={16} /></Link></div></StaggerItem></StaggerContainer>
           <div className="hidden justify-self-end md:block"><div className="w-64 border-l border-[#d9ad51]/50 pl-6"><p className="font-display text-5xl text-[#d9ad51]">18</p><p className="mt-1 text-sm leading-5 text-[#ead9cc]">key projects across prime destinations in Egypt.</p><div className="mt-8 h-px bg-[#ead8ba]/25" /><p className="mt-4 text-xs uppercase tracking-[.15em] text-[#ead9cc]">NAC · Zayed · October · New Cairo</p></div></div>
        </div>
         <FadeIn delay={0.3} className="absolute bottom-0 z-10 left-1/2 w-[calc(100%-28px)] max-w-[1040px] -translate-x-1/2 translate-y-1/2 rounded-2xl border border-[#e6d1ac] bg-[#fff9ef] p-4 text-[#56293a] shadow-[0_20px_50px_rgba(50,20,30,.2)] md:p-5"><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.12em] text-[#9b702c]"><Sparkles size={14} /> Start with what matters to you</div><div className="grid gap-2 md:grid-cols-[1fr_1fr_1fr_auto]"><label className="rounded-xl border border-[#eadbc4] bg-[#fffdf8] px-4 py-2"><span className="block text-[10px] uppercase tracking-[.12em] text-[#967b70]">I’m looking in</span><select value={city} onChange={(e) => setCity(e.target.value)} className="w-full bg-transparent pt-1 text-sm font-bold outline-none" data-testid="select-search-city"><option value="all">Any city</option><option value="New Administrative Capital">New Administrative Capital</option><option value="Sheikh Zayed">Sheikh Zayed</option><option value="6th of October">6th of October</option><option value="New Cairo">New Cairo</option></select></label><label className="rounded-xl border border-[#eadbc4] bg-[#fffdf8] px-4 py-2"><span className="block text-[10px] uppercase tracking-[.12em] text-[#967b70]">My budget</span><select value={budget} onChange={(e) => setBudget(e.target.value)} className="w-full bg-transparent pt-1 text-sm font-bold outline-none" data-testid="select-search-budget"><option value="all">Any budget</option><option value="under">Under EGP 3m</option><option value="over">EGP 3m and above</option></select></label><label className="rounded-xl border border-[#eadbc4] bg-[#fffdf8] px-4 py-2"><span className="block text-[10px] uppercase tracking-[.12em] text-[#967b70]">I need a</span><select value={type} onChange={(e) => setType(e.target.value)} className="w-full bg-transparent pt-1 text-sm font-bold outline-none" data-testid="select-search-type"><option value="all">Any home type</option><option value="apartment">Apartment</option><option value="townhouse">Townhouse</option><option value="duplex">Duplex</option><option value="Commercial">Commercial</option><option value="Administrative">Administrative</option><option value="Medical">Medical</option></select></label><a href="#projects" className="flex items-center justify-center gap-2 rounded-xl bg-[#56293a] px-5 py-3 text-sm font-bold text-[#fff9ef]" data-testid="button-search-projects">See projects <ArrowRight size={15} /></a></div><p className="mt-3 text-xs text-[#8a7167]" data-testid="text-search-results">{filtered.length} project{filtered.length === 1 ? '' : 's'} match your search</p></FadeIn>
      </section>

      <section id="projects" className="container-shell scroll-mt-8 pb-20 pt-36 md:pb-28 md:pt-44"><div className="flex items-end justify-between gap-6"><SectionHeading eyebrow="Find your footing" title="Projects built for real life." copy="No mystery listings. Just the location, the numbers, and the details you need to decide with confidence." /><Link href="/contact" className="hidden items-center gap-2 pb-2 text-sm font-bold text-[#9b702c] md:flex" data-testid="link-view-all-projects">Talk to a specialist <ArrowRight size={15} /></Link></div>{filtered.length > 0 ? <StaggerContainer className="mt-10 grid gap-5 md:grid-cols-3">{filtered.map((project, index) => <StaggerItem key={project.slug} className={index === 0 && filtered.length > 1 ? 'md:col-span-2' : ''}><ProjectCard project={project} featured={index === 0 && filtered.length > 1} /></StaggerItem>)}</StaggerContainer> : <div className="mt-10 rounded-2xl border border-dashed border-[#d9c5a5] p-12 text-center"><HomeIcon className="mx-auto text-[#b88a36]" size={28} /><h3 className="mt-4 font-display text-2xl text-[#56293a]">Nothing quite fits that search.</h3><p className="mt-2 text-sm text-[#735e57]">Try a wider budget or ask our team for homes coming soon.</p><button onClick={() => { setCity('all'); setBudget('all'); setType('all'); }} className="mt-5 rounded-full bg-[#56293a] px-5 py-2.5 text-sm font-bold text-[#fff8ea]" data-testid="button-reset-search">Reset search</button></div>}</section>

      <section id="why-us" className="bg-[#eadbc4] py-20 md:py-28"><div className="container-shell grid gap-12 md:grid-cols-[.85fr_1.15fr] md:items-end"><div><SectionHeading eyebrow="Why Capital Hills" title="Invest With Trust." copy="We believe real estate is more than a property. It is a decision about your future, your family, your business, and your investment." /><Link href="/why-us" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#9b702c]" data-testid="link-home-why-us">Learn more about us <ArrowRight size={15} /></Link></div><StaggerContainer className="grid gap-px overflow-hidden rounded-2xl bg-[#cdb590] sm:grid-cols-2"><StaggerItem className="bg-[#f4e8d6] p-6 h-full"><ShieldCheck className="text-[#9b702c]" size={25} /><h3 className="mt-12 font-display text-2xl text-[#56293a]">Trusted relationships</h3><p className="mt-2 text-sm leading-6 text-[#735e57]">Creating spaces where people can live, work, grow, and connect.</p></StaggerItem><StaggerItem className="bg-[#f4e8d6] p-6 h-full"><BadgeCheck className="text-[#9b702c]" size={25} /><h3 className="mt-12 font-display text-2xl text-[#56293a]">18 key projects</h3><p className="mt-2 text-sm leading-6 text-[#735e57]">Serving different needs across residential and mixed-use developments.</p></StaggerItem><StaggerItem className="bg-[#f4e8d6] p-6 h-full"><CalendarDays className="text-[#9b702c]" size={25} /><h3 className="mt-12 font-display text-2xl text-[#56293a]">Established partners</h3><p className="mt-2 text-sm leading-6 text-[#735e57]">Working with brands across industries to deliver lasting value.</p></StaggerItem><StaggerItem className="bg-[#56293a] p-6 text-[#fff7e9] h-full"><CircleCheck className="text-[#d9ad51]" size={25} /><h3 className="mt-12 font-display text-2xl">Our people at the heart</h3><p className="mt-2 text-sm leading-6 text-[#e2cbbd]">Creating a collaborative environment where our teams can grow.</p></StaggerItem></StaggerContainer></div></section>

      <section className="bg-[#56293a] py-20 text-[#fff7e9] md:py-28"><div className="container-shell"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading light eyebrow="For a limited time" title="A little more room to make your move." copy="Our current offers are designed to help you get settled, not rush you into a decision." /><Link href="/contact" className="inline-flex items-center gap-2 text-sm font-bold text-[#d9ad51]" data-testid="link-offers-contact">Ask about an offer <ArrowRight size={15} /></Link></div><StaggerContainer className="mt-10 grid gap-4 md:grid-cols-3">{projects.map((project, index) => <StaggerItem key={project.slug} className="rounded-2xl border border-[#ead8ba]/20 bg-[#6a3749] p-5"><p className="text-xs text-[#dbbfaa]">{project.name}</p><h3 className="mt-10 font-display text-2xl">{project.offer}</h3><Link href={`/projects/${project.slug}`} className="mt-8 inline-flex items-center gap-2 text-xs font-bold text-[#d9ad51]" data-testid={`link-offer-${index}`}>View project <ArrowRight size={14} /></Link></StaggerItem>)}</StaggerContainer></div></section>

      <section className="container-shell py-20 md:py-28"><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr]"><div><SectionHeading eyebrow="Kind words" title="The part that matters after the viewing." copy="People remember how a home-buying decision felt. Here is what some of our homeowners told us." /><Link href="/contact" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#9b702c]" data-testid="link-all-reviews">See all reviews <ArrowRight size={15} /></Link></div><FadeIn className="relative rounded-2xl bg-[#eadbc4] p-7 md:p-10"><div className="mb-10 flex items-center gap-1 text-[#b88a36]">{[1,2,3,4,5].map((item) => <Sparkles key={item} size={15} fill="currentColor" />)}</div><blockquote className="font-display text-3xl leading-tight text-[#56293a] md:text-4xl">“{reviews[review].quote}”</blockquote><div className="mt-8 flex items-end justify-between"><div><p className="text-sm font-bold text-[#56293a]">{reviews[review].name}</p><p className="mt-1 text-xs text-[#735e57]">{reviews[review].detail}</p></div><div className="flex gap-2"><button onClick={() => setReview((review - 1 + reviews.length) % reviews.length)} className="grid h-9 w-9 place-items-center rounded-full border border-[#cdb590] text-[#56293a]" aria-label="Previous review" data-testid="button-previous-review"><ChevronLeft size={16} /></button><button onClick={() => setReview((review + 1) % reviews.length)} className="grid h-9 w-9 place-items-center rounded-full border border-[#cdb590] text-[#56293a]" aria-label="Next review" data-testid="button-next-review"><ChevronRight size={16} /></button></div></div></FadeIn></div></section>

      <section className="bg-[#f1e6d6] py-20 md:py-28"><div className="container-shell"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><SectionHeading eyebrow="From the journal" title="Useful things to know." copy="Short reads for a clearer home-buying decision." /></div><Link href="/contact" className="inline-flex items-center gap-2 text-sm font-bold text-[#9b702c]" data-testid="link-all-journal">Read more articles <ArrowRight size={15} /></Link></div><StaggerContainer className="mt-10 grid gap-5 md:grid-cols-3"><StaggerItem><article className="group"><img src="https://images.pexels.com/photos/7031603/pexels-photo-7031603.jpeg?auto=compress&cs=tinysrgb&w=900" alt="Modern home exterior" className="h-52 w-full rounded-2xl object-cover transition group-hover:brightness-90" /><p className="mt-5 text-xs font-bold uppercase tracking-[.13em] text-[#9b702c]">Buying well · 5 min read</p><h3 className="mt-2 font-display text-2xl text-[#56293a]">What to check before you pay a property deposit</h3><p className="mt-2 text-sm leading-6 text-[#735e57]">A practical list for asking the right questions early.</p></article></StaggerItem><StaggerItem><article className="group"><img src="https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=900" alt="Terrace homes in warm light" className="h-52 w-full rounded-2xl object-cover transition group-hover:brightness-90" /><p className="mt-5 text-xs font-bold uppercase tracking-[.13em] text-[#9b702c]">The neighbourhood · 4 min read</p><h3 className="mt-2 font-display text-2xl text-[#56293a]">Why the right commute changes a home completely</h3><p className="mt-2 text-sm leading-6 text-[#735e57]">Look beyond the walls. The daily route matters.</p></article></StaggerItem><StaggerItem><article className="group"><img src="https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=900" alt="Bright contemporary living room" className="h-52 w-full rounded-2xl object-cover transition group-hover:brightness-90" /><p className="mt-5 text-xs font-bold uppercase tracking-[.13em] text-[#9b702c]">Money matters · 6 min read</p><h3 className="mt-2 font-display text-2xl text-[#56293a]">How to read a property payment plan</h3><p className="mt-2 text-sm leading-6 text-[#735e57]">The difference between a manageable plan and a stressful one.</p></article></StaggerItem></StaggerContainer></div></section>

      <section className="container-shell py-20 md:py-28"><div className="grid overflow-hidden rounded-2xl bg-[#c49743] md:grid-cols-[1.1fr_.9fr]"><FadeIn className="p-8 md:p-14"><p className="eyebrow text-[#56293a]">One good conversation</p><h2 className="mt-4 max-w-md font-display text-4xl leading-tight text-[#3c1d2a] md:text-5xl">Let’s find the place that makes sense for you.</h2><p className="mt-5 max-w-sm text-sm leading-6 text-[#56293a]/80">Tell us your city, your range, and what you need. We will come back with useful options, not a sales pitch.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#56293a] px-5 py-3 text-sm font-bold text-[#fff7e9]" data-testid="link-contact-cta">Start a conversation <ArrowRight size={15} /></Link></FadeIn><div className="relative min-h-[270px] overflow-hidden"><img src="https://images.pexels.com/photos/7031612/pexels-photo-7031612.jpeg?auto=compress&cs=tinysrgb&w=1000" alt="Family home exterior" className="absolute inset-0 h-full w-full object-cover mix-blend-multiply opacity-80" /></div></div></section>
    </main>
  </Shell>;
}